config/routes.rb
Rails.application.routes.draw do

  get 'users/autocomplete' , to: 'users#autocomplete'
  get 'articles/:id/edit/crop', to: 'articles#crop' , as: "crop_featured_image"
  get 'updates/:id/edit/crop', to: 'updates#crop' , as: "crop_promo"
  get 'users/:id/edit/crop', to: 'users#crop' , as: "crop_avatar"

  resources :updates
  resources :pages
  resources :users, constraints: {id: /[0-9A-Za-z\-\.]+/ }
  resources :notifications

  resources :assignments do
    member do
      get 'workflow'
    end
  end

  mount Ckeditor::Engine => '/editor'
  resources :newsletters do
    member do
      get :mail
      get :preview
    end
  end

  resources :comments do
    member do
      get :accept
      get :reject
      get :reply
      post :reply
    end
  end

  devise_for :user, :path => 'account', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  root 'pages#home'

  resources :articles , path: 'node' , except: :index do
    member do
      get :workroom
      post :workroom , action: 'workroom_save'
      get 'version/:version', action: 'version' , as: "version"
      delete 'version/:version', action: 'destroy_version' , as: "destroy_version"
      get :assign
      post :assign , action: 'assign_save' , as: 'assign_save'
      patch :assign , action: 'assign_save'
    end
  end

  namespace :admin do
    root to: 'pages#index'
    resources :articles
    resources :comments
    resources :task_types
    resources :errors , except: [:new,:create,:update,:edit]
    resources :categories do
      member do
        get :remove
      end
    end
    get :assignments, to: 'pages#assignments'
    get :stats , to: 'stats#index'
  end

  get '/account/password' , to: 'users#password_changed'

  get '/:category' , to: 'articles#index' , as: 'category'

end

app/models/article.rb
class Article < ActiveRecord::Base
belongs_to :user
has_many :comments , as: :commentable
has_many :assignments , as: :assignable
has_many :events , class_name: "Ahoy::Event" , as: :trackable
belongs_to :category
scope :published, -> { where(workflow_state: ["published","featured"]) }
attr_accessor :remarks

# Tip:
# Keep min. width of the image 700-900px, so that the same images can be used
# for craeation of wide covers later on should we change the layout

# PAPERTRAIL
has_paper_trail only: [:title, :body, :intro] , on: [:update]

# PAPERCLIP
has_attached_file :cover,
                  styles: { :large => "800x400>", :medium => "267x200>" , :thumb => "100x75>" },
                  :default_url => "paperclip_defaults/articles/covers/:style/missing.jpg"

# VALIDATIONS
validates_presence_of :title , :body, :category_id
validates_length_of :body , in: 320..25000
validates_length_of :intro , maximum: 160
validates :cover, :dimensions => { :width => 800, :height => 400 }
validates_attachment  :cover,
                      content_type: { content_type: /\Aimage\/.*\Z/ },
                      size: {in: 0..4000.kilobytes}

# PAPERCROP (ezuhaib/papercrop)
crop_attached_file :cover , min_size:'800x400' , aspect:'2:1'

# PUBLIC ACTIVITY
include PublicActivity::Model

# WORKFLOW
include Workflow
workflow do

  state :awaiting_assignment do
    event :assign, transitions_to: :assigned , meta: {hide: true}
    event :reject, transitions_to: :cold_rejected
  end

  state :assigned do
    event :publish, transitions_to: :published
    event :reject, transitions_to: :warm_rejected
  end

  state :published
    event :unpublish , transitions_to: :unpublished, meta: {friendly: 'Yank out'}

  state :cold_rejected do
    event :unreject, transitions_to: :awaiting_assignment
  end

  state :warm_rejected do
    event :unreject, transitions_to: :assigned
  end

  state :unpublished do
    event :publish, transitions_to: :published
    event :reject, transitions_to: :warm_rejected
  end

end

# EVENT HANDLERS
def feature
  @previously_featured = Article.where(workflow_state: 'featured').first
  @previously_featured.try(:unfeature!)
end

def assigned_to?(user,roles=nil)
  assignments = self.assignments.active.where(to_id:user.id)
  if roles == nil
    return true if assignments.any?
  elsif roles.is_a? Array
    roles = roles.map { |x| x.to_s }
    return true if (assignments.pluck(:tag) & roles).any?
  end
  return false
end

def editing_assignment
  self.assignments.active.where(tag: 'editing').first
end

def subediting_assignment
  self.assignments.active.where(tag: 'subediting').first
end

def custom_assignments
  self.assignments.active.where(tag: 'custom').all
end

def latest_version
  self.versions.last.id
end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController

set_tab :articles

def index
  authorize! :moderate , Article
  if params[:show] == "all"
    @articles = Article.all
  elsif params[:show] == "rejected"
    @articles = Article.where(workflow_state: 'rejected')
  elsif params[:show] == "assigned"
    @articles = Article.where(workflow_state: 'assigned')
  else
    @articles = Article.where(workflow_state: ['awaiting_assignment'])
  end
end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :workroom, :workroom_save, :edit, :update, :destroy,
    :crop, :version, :destroy_version, :assign, :assign_save]

  # GET /articles
  # GET /articles.json
  def index
    authorize! :read , Article
    @feature = Article.where(workflow_state: 'featured').first
    if params[:category] and Category.where(slug:params[:category]).present?
      @cat = Category.where(slug:params[:category]).first
      ahoy.track "navigation_page" , {} , trackable: @cat
      @page_title  = @cat.name
      @page_description = @cat.description
      set_tab @cat.slug
      @articles = @cat.articles.published.order('created_at DESC').page(params[:page]).per(5)
      render 'category_articles'
    elsif params[:category] # if a category is specified but doesn't exist
      raise ActionController::RoutingError.new("No route or channel for: #{params[:category]}")
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    authorize! :read , @article
    @page_title  = @article.title
    @page_description = @page_description  = teaser(@article.body)
    @more = @cat.articles.published.first(5)
    @og_image = @article.cover(:large)
    ahoy.track "readable_content" , {} , trackable: @article unless @article.user == current_user
    authorize! :read_unpublished , @article unless @article.published?
    @comment = Comment.where(commentable: @article).new
    @comments = @article.comments.where(workflow_state: 'accepted').arrange
  end

  def workroom
    authorize! :work , @article
    @page_title = "WorkRoom for #{@article.title}"
    @page_description = "Editorial tasks section for the user-submitted nodes."
    @activities = @article.activities.where.not(key: 'article.commented').order('created_at DESC')
    @assignments = @article.assignments
    @hide_sidebar = true
  end

  def workroom_save
    #todo: validate this input
    #todo: more granular permissions MUST be here
    #todo: the user may have to be notified about some of the actions here
    authorize! :work , @article
    @article.create_activity params[:button], owner: current_user, parameters:{remarks: params[:remarks]}
    if @article.current_state.events.include? params[:button].to_sym
      @article.send(params[:button]+"!")
    end
    redirect_to :back
  end

  def version
    authorize! :read_versions , @article
    @page_title  = "Previous versions of #{@article.title}"
    @ver = params[:version]
    if @ver
      if @ver == "original"
        @editor = @article.user
        @article = @article.versions.first.reify
        @article_prev = nil
      else
        @editor = User.find(@article.previous_version.originator)
        @article = @article.versions.find(@ver).next.try(:reify) || @article
      end
    end
  end

  def assign
    authorize! :assign , @article
    @page_title  = "Assigning node"
    @teammates = Role.where(title: 'teammate').first.try(:users)
    @assignments = @article.assignments
    @assignment = Assignment.new(assignable: @article)
    @hide_sidebar = true
    if @teammates.blank?
      flash[:error] =  "No Sayaahi Teammates defined so far"
      redirect_to :back
    end
  end

  def assign_save
    authorize! :assign , @article
    @page_title  = "Assigning node"
    @assignments = @article.assignments
    @assignment = Assignment.new(assignment_params)
    @assignment.by_id = current_user.id
    @teammates = Role.where(title: 'teammate').first.try(:users)

    if @assignment.save
      @article.assign! if @article.awaiting_assignment?
      @article.create_activity :assign , owner: @assignment
      flash[:success] = "Task assignment successful"
      @article.assign! if @article.awaiting_assignment?
      redirect_to workroom_article_path
    else
      flash[:error] = "There was an error"
      render :assign
    end
  end

  # GET /articles/new
  def new
    authorize! :create , Article
    @page_title  = "New article submission"
    @article = Article.new
    if params[:cat]
      @cat = Category.find(params[:cat])
      set_tab @cat.name
    end
  end

  # GET /articles/1/edit
  def edit
    authorize! :update , @article
    @page_title  = "Editing #{@article.title}"
    if params[:version]
      @ver = params[:version]
      @article = @article.versions.find(@ver).next.try(:reify) || @article
    end
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    authorize! :create , @article
    if params[:article][:cover] && @article.save
      redirect_to crop_cover_path (@article)
    elsif @article.save
      @article.create_activity :create , owner: current_user
      redirect_to @article, notice: "Article submitted for approval. You'll be notified upon aproval"
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    authorize! :update , @article
    @article.assign_attributes(article_params)
    @category_change = @article.category_id_change
    @article_body_or_title_changed = (@article.body_changed? or @article.title_changed?)
    @article.save

    # By now the node is already saved.

    if @article.errors.any?
      flash[:error] = @article.errors.full_messages_for(:body).first
      render :edit
    elsif params[:article][:cover] && @article.save
      redirect_to action: :crop
    else
      @article.create_activity :update , owner: current_user ,
                                parameters: {version: @article.versions.last.id, remarks: params[:article][:remarks]} if @article_body_or_title_changed

      @article.create_activity  :category_changed , owner: current_user , recipient: @article.user,
                                parameters: {from: @category_change[0] , to: @category_change[1]} if @category_change

      redirect_to @article, notice: 'Article was successfully updated.'
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    authorize! :destroy , @article
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def crop
    authorize! :update , @article
    @page_title  = "Article image cropping"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
      @cat = @article.category
      set_tab @cat.name
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :cover, :category_id, :created_at , :intro, cropping_params(:cover))
    end

    def assignment_params
      params.require(:assignment).permit(:by_id, :to_id, :assignable_id, :assignable_type, :tag, :deadline, :body, :title)
    end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_category_sugar.erb
<div class="row">
<div class="col-sm-2 hidden-sm">
	<div id="index_left" style="background-color: <%= @cat.color_dark || "#333" %>" >
	  <%= fa_icon @cat.icon , class: 'fa-5x' %>
	  <h1><%= @cat.name %></h1>
	  <p><%= @cat.description %></p>
	</div>

	<%# Later on, we do not want to hiden advertisements on any views %>
	<div id="subindex_left" class="hidden-xs hidden-sm" style="background-color: <%= @cat.color_light || "#ccc" %>">
    <p>Got anything?</p>
    <%= link_to "Post Now" , new_article_path(cat: @cat.id) , class:"btn btn-primary" %>
  </div>
</div>

<div class="col-sm-8 col-md-7 col-lg-6">
<%= yield %>
</div>

<div class="col-sm-4 col-md-3 col-lg-4 pull-right">
	<div id="ad" class="hidden-sm" "><%= render 'shared/ads' %></div>
	<% unless @hide_sidebar == true %>
		<div id="index_right" class="col-xs-12" style="background-color: <%= @cat.color_light || "#ccc" %>" >
			<%= content_for?(:index_right) ? yield(:index_right) : @cat.intro.html_safe %>
		</div>
	<% end %>
	<div id="subindex_right" class="col-xs-12"><%= yield(:subindex_right) %></div>
</div>

</div>

app/views/articles/_form.html.erb
<%= bootstrap_form_for(@article, :html => { :multipart => true}) do |f| %>
    <%= f.text_field :title , hide_label: true , placeholder: "A title for this submission" %>
    <%= f.cktext_area :body , height: '180', hide_label: true , placeholder: "Here you go..." %></br>
    <%= f.file_field :cover %>
    <%# f.text_field :created_at , "data-behaviour"=>"datepicker", placeholder: "yyyy/mm/dd" %>
    <%= f.hidden_field :category_id , value: @cat.id %>
    <% if can? :superedit , @article and !@article.new_record? %>
      <%= f.collection_select :category_id , Category.all , :id , :formatted_name , prompt: "Select Category" %>
      <%= f.text_field :created_at , "data-behaviour" => "datetimepicker" , placeholder: "yyyy-mm-dd" , value: @article.created_at.strftime('%Y %B %d, %k:%M ') , icon: 'calendar' %>
    <% end %>
    <%= f.text_field :remarks , label: "Editing remarks" , placeholder: "What was edited?" , icon: 'comment' unless @article.new_record?%>
    <%= f.form_group do %>
      <%= f.submit 'Submit' , class: 'btn btn-success' %>
    <% end %>
<% end %>

app/views/articles/_versions_list.html.erb
<% if can? :read_versions , @article %>

<h3>
    Versions <b>(<%= @article.versions.length + 1 %>)</b>
</h3>
  <% @article.versions.reverse.each do |a| %>
    <%= link_to pretty_created_at(a),
    				version_article_path(@article , a),
    				class: ('version-active' if a.id == @ver.to_i or (!@ver and @article.latest_version == a.id)) %>
  </br>
  <% end %>
<%= link_to 'Original Version', version_article_path(@article, :original) , class: ("version-active" if @ver == 'original') %>

<% end %>

app/views/articles/_workflow_form_controls.html.erb
<%= fields_for @article do |f| %>
  <%= f.button 'Comment', value: 'workroom.comment', class: 'btn btn-default' %>
  <%= link_to 'Edit Node', edit_article_path(@article) , class: "btn btn-default" if can? :update , @article %>
  <%= link_to 'Assignment', assign_article_path(@article) , class: "btn btn-default" if can? :manage , Assignment %>
  <%= workflow_form_controls(@article) if can? :superedit , @article %>
<% end %>

app/views/articles/assign.html.erb
<%= render layout: 'category_sugar' do %>

<h4>WorkRoom for <%= link_to @article.title , @article %></h4>

<div class="alert-dark">Task creation and assignments dashboard</div>

<%= bootstrap_form_for @assignment , url: :assign_save_article , layout: :horizontal do |f| %>
	<%= f.collection_select :to_id , @teammates, :id, :username, {label: 'Assignee'} , class: 'selectpicker' %>
	<%= f.text_field :deadline , "data-behaviour" => "futurepicker" , placeholder: "yyyy-mm-dd" , value: @assignment.deadline.try(:to_date) %>
	<%= f.text_area :body, label: 'Remarks' , placeholder: 'Please add any extra remarks or guildelines for the editor here' %>
	<%= f.hidden_field :assignable_id %>
	<%= f.hidden_field :assignable_type %>
	<%= f.collection_select :tag , TaskType.where(assignable_type: 'Article'), :key, :title, {label: 'Nature'}, class: 'selectpicker show-tick'%>
	<div id="title_field" class:"hidden"><%= f.text_field :title %></div>
	<%= f.form_group do %>
		<%= f.submit :Assign , class: 'btn btn-danger' %>
		<%= link_to :Cancel , workroom_article_path , class: 'btn btn-default' %>
	<% end %>
<% end %>

<%= render 'shared/workroom_sidebar' %>

<% end %>

<script>
function toggle_title_field(trigger_field){
	if( trigger_field.val() == 'custom'){
			$('#title_field').show();
	}else{
			$('#title_field').hide();
	}
}

$('#assignment_tag').change(function(){
	toggle_title_field($(this));
});

$(document).ready(function(){
	toggle_title_field($('#assignment_tag'));
})
</script>

app/views/articles/category_articles.erb
<%= render layout: "category_sugar" do %>

<% if @feature %>
  <div id="featured" class="col-lg-7">
    <div class="pull-left article-thumb">
      <%= image_tag @feature.cover(:medium) , height: "140px" %>
    </div>

    <div>
      <h6>Featured today</h6>
      <h4><%= link_to @feature.title , @feature %></h4>
      <p><%= @feature.intro %></p>
    </div>
  </div>
<% end %>

<% @articles.each do |a| %>
  <div class="article-index-entry">
    <h4><%= link_to a.title , a %></h4>
    <p>
      <span class="avatar avatar-inline"><%= image_tag a.user.avatar(:inline) %></span>
      <%= link_to a.user.username , a.user %> · <%= time_ago(a.created_at) %>
    </p>
  </div>
<% end %>
<%= "Nothing yet" if @articles.blank? %>

<% end %>

app/views/articles/crop.html.erb
<div class="alert alert-info">
Ideally the image must be made of resolution 800x400 by hand. If it isn't then crop it here.</div>

<%= form_for @article do |f| %>
  <div class="center">
  	<%= f.cropbox :cover , width: 800 %></div></br>
  	<div class='well col-xs-12'>
  		<%= f.crop_preview :cover , width: 350 %>
  			<b>Save if you're satisfied</b></br></br>
  			<%= f.submit 'Save' , class:"btn btn-success btn-lg" %>
  	</div>
<% end %>

app/views/articles/feature.html.erb
<h2>Featuring <%= link_to @article.title , @article %></h2>
<div class="alert alert-success">The featuring workflow is work-in-progress. Currently only one article can be featured at a time. In later updates, you can pre-assign featured articles date-wise so that most of the "daily feature" system is automated.</div>

<%= form_tag :feature_article do %>
	<%= submit_tag "Whatever. Just feature this" , class: 'btn btn-danger' %>
<% end %>

app/views/articles/index.html.erb
<h1>Placeholder</h1>
<h3>For a public facing global node index</h3>

app/views/articles/new.html.erb
<%= render layout: "category_sugar" do %>
<div class="alert-dark">Read the column on the right for submission guidelines</div>
<h4>New Submission</h4>
<%= render 'form' %>
<% end %>

app/views/articles/reject.html.erb
</br><div class="alert alert-danger">
	<b>IMPORTANT</b></br>
	<p>Since we would rarely be rejecting content, this feature isn't implemented yet. Expect it to roll out in the next sayaahi update</p>
</div>

<h2>Rejecting <%= link_to @article.title , @article %></h2>
<div class="alert alert-success">It is polite to let the submitter know why this content was rejected. Please note that if the rejection was due to trivial reasons that you can fix as an editor, you may freely do so as per the sayaahi terms and conditions.</div>

<%= form_tag :reject_article do %>
	<%= text_area_tag :reason ,nil, id: 'edit',
						placeholder: 'Please provide the reason for rejection' %></br>
	<%= submit_tag :submit , class: 'btn btn-danger' %>
<% end %>

app/views/articles/show.html.erb
<%= render layout: 'category_sugar' do %>

<h1>
  <%= @article.title %>
  <%= link_to fa_icon(:pencil), edit_article_path , class:"small" if can? :edit , @article %>
  <%= link_to fa_icon(:flask), workroom_article_path , class:"small" if can? :work , @article %>
</h1>

<%= image_tag @article.cover(:large) , class: "responsive article-cover" if @article.cover.exists? %>

<p class="small">By <%= link_to "Sayaahi Team" , user_path('sayaahi.team')  %> · <b><%= @article.created_at.strftime('%b %d, %Y') %></b></p>

<%= @article.body.html_safe %>

<div id="comments_area" class="col-xs-11" %>
  <h3>Comments</h3>
  <%= nested_comments @comments %>
  <% unless current_user %>
  <div class="alert alert-danger small">
  You are commenting as a guest. As a result you cannot edit the comment once you post it. Also, the comment shall be approved by a moderator before going public. You may consider <%= link_to "signing up." , new_user_registration_path %>
  </div>
  <% end %>
  <%= render 'comments/form' %>
</div>

<%= content_for :subfooter do %>
    <div class="col-sm-offset-2 col-sm-4">
      <table class="table">
        <h4><%= fa_icon 'plus-circle' %> More <%= @cat.name.pluralize %></h4>
        <% @more.each do |a| %>
          <tr>
            <td><%= link_to a.title , a %></td>
          </tr>
        <% end %>
        <%= "<h3>Nothing yet :'(</h3>".html_safe if @more.blank? %>
      </table>
    </div>
<% end %>

<% end %>

app/views/articles/version.html.erb
<%= render layout: 'category_sugar' do %>

<div class="col-lg-12">
  <h4>
    Version #<%= @ver %>&nbsp&nbsp
    <%= link_to 'Use' , edit_article_path(@article, version: @ver) , class: 'btn btn-default btn-sm' %>
  </h4>

  <h1><%= xdiff(@article.previous_version.try(:title),@article.title) %></h1>

  <div class="alert-dark">This edit by: <%= link_to @editor.username , @editor %></div>

  <p><%= xdiff(@article.previous_version.try(:body),@article.body) %></p>

  <div><b><%= link_to @article.user.username , @article.user %></b> · <%= @article.created_at.strftime('%b %d') %></div>
</div>


<% content_for :index_right do %>
  <%= render 'versions_list' %>
<% end %>

<% end %>

app/views/articles/workroom.html.erb
<%= render layout: 'category_sugar' do %>
<h4>WorkRoom for <%= link_to @article.title , @article %></h4>

<%= bootstrap_form_tag path: workroom_article_path do |f| %>
	<%= f.text_area :remarks %>
	<%= render 'workflow_form_controls' %>
<% end %></br>

<% @activities.each do |activity| %>
  <div class= "activity activity-<%= activity.key.gsub(/[._]/,'-') %>" >
    <div class="icon"></div>
    <div class="main">
      <%= render_activity activity , root: 'public_activity/feeds' %>
    </div>
    <div class="time"><%= time_ago(activity.created_at) %></div>
  </div>
<% end %>

<%= render 'shared/workroom_sidebar' %>

<% end %>