config/routes.rb
Rails.application.routes.draw do

  get 'users/autocomplete' , to: 'users#autocomplete'
  get 'articles/:id/edit/crop', to: 'articles#crop' , as: "crop_featured_image"
  get 'updates/:id/edit/crop', to: 'updates#crop' , as: "crop_promo"
  get 'users/:id/edit/crop', to: 'users#crop' , as: "crop_avatar"

  resources :updates
  resources :pages
  resources :users, constraints: {id: /[0-9A-Za-z\-\.]+/ }
  resources :notifications

  resources :assignments do
    member do
      get 'workflow'
    end
  end

  mount Ckeditor::Engine => '/editor'
  resources :newsletters do
    member do
      get :mail
      get :preview
    end
  end

  resources :comments do
    member do
      get :accept
      get :reject
      get :reply
      post :reply
    end
  end

  devise_for :user, :path => 'account', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  root 'pages#home'

  resources :articles , path: 'node' , except: :index do
    member do
      get :workroom
      post :workroom , action: 'workroom_save'
      get 'version/:version', action: 'version' , as: "version"
      delete 'version/:version', action: 'destroy_version' , as: "destroy_version"
      get :assign
      post :assign , action: 'assign_save' , as: 'assign_save'
      patch :assign , action: 'assign_save'
    end
  end

  namespace :admin do
    root to: 'pages#index'
    resources :articles
    resources :comments
    resources :task_types
    resources :errors , except: [:new,:create,:update,:edit]
    resources :categories do
      member do
        get :remove
      end
    end
    get :assignments, to: 'pages#assignments'
    get :stats , to: 'stats#index'
  end

  get '/account/password' , to: 'users#password_changed'

  get '/:category' , to: 'articles#index' , as: 'category'

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
validates_presence_of :title , :body , :category

def self.categories
  {
    "Global (send to everyone)" => :global,
    "Important (send to those subscibed) NOT IMPLEMENTED" => :important
  }
end

def liquid_legend(user)
  {
    "username" => user.username,
    "join_date" => user.created_at.strftime("%d %B, %Y")
  }
end

end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_action :set_newsletter, only: [:show, :edit, :update, :destroy, :mail, :preview]
  before_action :authorize

  def mail
    if params[:test] == 'true'
      NewsletterMailer.main(@newsletter,User.first).deliver
    else
      User.find_each do |user|
        NewsletterMailer.main(@newsletter,user).deliver
      end
    end
    flash[:notice] = "Mail placed in queue"
    redirect_to @newsletter
  end

  def preview
    @body = Liquid::Template.parse(@newsletter.body)
    render layout: false
  end

  # GET /newsletters
  # GET /newsletters.json
  def index
    @newsletters = Newsletter.all
    @page_title  = "Newsletters list"
  end

  # GET /newsletters/1
  # GET /newsletters/1.json
  def show
    @body = Liquid::Template.parse(@newsletter.body)
    @page_title  = @newsletter.title
  end

  # GET /newsletters/new
  def new
    @newsletter = Newsletter.new
    @page_title  = "Creating new newsletter"
  end

  # GET /newsletters/1/edit
  def edit
    @page_title  = "Editing newsletter"
  end

  # POST /newsletters
  # POST /newsletters.json
  def create
    @newsletter = Newsletter.new(newsletter_params)

    respond_to do |format|
      if @newsletter.save
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully created.' }
        format.json { render :show, status: :created, location: @newsletter }
      else
        format.html { render :new }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletters/1
  # PATCH/PUT /newsletters/1.json
  def update
    respond_to do |format|
      if @newsletter.update(newsletter_params)
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully updated.' }
        format.json { render :show, status: :ok, location: @newsletter }
      else
        format.html { render :edit }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json
  def destroy
    @newsletter.destroy
    respond_to do |format|
      format.html { redirect_to newsletters_url, notice: 'Newsletter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter
      @newsletter = Newsletter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsletter_params
      params.require(:newsletter).permit(:title, :body, :category)
    end

    def authorize
      authorize! :mail , User
    end
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/newsletters/_form.html.erb
<%= bootstrap_form_for @newsletter , layout: :horizontal , label_col: "col-md-1 col-xs-2" do |f| %>

  <%= f.text_field :title %>
  <%= f.text_area :body , id: 'edit' %>
  <%= f.select :category , Newsletter.categories %>
  <%= f.form_group do %>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/newsletters/_status.html.erb
<% if @newsletter.try(:mailed?) %>
	<div class="label label-success">Sent</div>
<% else %>
	<div class="label label-danger">Not sent</div>
<% end %>	

app/views/newsletters/edit.html.erb
<h1>Editing newsletter</h1>

<%= render 'form' %>

app/views/newsletters/index.html.erb
<h1>Newsletters Control &nbsp<%= link_to 'Create', new_newsletter_path , class: "btn btn-default" %></h1>
<div class="alert alert-info">
Welcome to the newsletters control. Use carefully since whatever we do here cannot be reversed.
</div>

<table class="table table-striped">

<% @newsletters.each do |newsletter| %>
  <tr>
    <td class="col-md-2 col-xs-3"><%= pretty_created_at(newsletter) %></td>
    <td class="col-md-1"><%= render 'status' , locals: newsletter %></td>
    <td><%= link_to newsletter.title , newsletter%>&nbsp
    <span class="badge"><%= newsletter.category %></span></td>
    <td><%= newsletter.mailed %></td>
  </tr>
<% end %>

</table>

<br>

app/views/newsletters/new.html.erb
<h1>New newsletter</h1>

<%= render 'form' %>

app/views/newsletters/preview.html.erb
<div style="max-width: 600px;margin-left:auto;margin-right:auto;">
<div style="background-color:#ccc;"><h1>Mail Preview</h1></div>
<%= render "newsletter_mailer/header" %>
<%= Premailer.new( @body.render(@newsletter.liquid_legend(User.first)).html_safe,
					with_html_string: true,
					css_string: Rails.application.assets.find_asset('mail.css').body
				).to_inline_css.html_safe %>
<%= render "newsletter_mailer/footer" %>
</div>

app/views/newsletters/show.html.erb
<div id="newsletter_sidebar" class="col-md-1 text-center">
  <div><%= @newsletter.created_at.strftime('<h2 class="subbed">%d</h2> %b').html_safe %></div>
  <div class="label label-primary"><%= @newsletter.category %></div>
  <%= render 'status' %>
</div>

<div class="col-md-11">
 <h3><%= link_to "Newsletters > " , newsletters_path %><%= @newsletter.title %></h3>
 <div id="mail_preview"><%= @body.render(@newsletter.liquid_legend(User.first)).html_safe %></div>
 <%= link_to "Edit" , edit_newsletter_path , class: "btn btn-default" %>
 <%= link_to "Preview" , preview_newsletter_path , class: "btn btn-default" %>
 <%= link_to "Test" , mail_newsletter_path(test: 'true') , class: "btn btn-success" %>
 <%= link_to "Send" , mail_newsletter_path , class: "btn btn-danger" %>
</div>