config/routes.rb
Rails.application.routes.draw do

  get 'users/autocomplete' , to: 'users#autocomplete'
  get 'articles/:id/edit/crop', to: 'articles#crop' , as: "crop_featured_image"
  get 'updates/:id/edit/crop', to: 'updates#crop' , as: "crop_promo"
  get 'users/:id/edit/crop', to: 'users#crop' , as: "crop_avatar"

  resources :updates
  resources :pages
  resources :users, constraints: {id: /[0-9A-Za-z\-\.]+/ }
  resources :notifications

  resources :assignments do
    member do
      get 'workflow'
    end
  end

  mount Ckeditor::Engine => '/editor'
  resources :newsletters do
    member do
      get :mail
      get :preview
    end
  end

  resources :comments do
    member do
      get :accept
      get :reject
      get :reply
      post :reply
    end
  end

  devise_for :user, :path => 'account', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  root 'pages#home'

  resources :articles , path: 'node' , except: :index do
    member do
      get :workroom
      post :workroom , action: 'workroom_save'
      get 'version/:version', action: 'version' , as: "version"
      delete 'version/:version', action: 'destroy_version' , as: "destroy_version"
      get :assign
      post :assign , action: 'assign_save' , as: 'assign_save'
      patch :assign , action: 'assign_save'
    end
  end

  namespace :admin do
    root to: 'pages#index'
    resources :articles
    resources :comments
    resources :task_types
    resources :errors , except: [:new,:create,:update,:edit]
    resources :categories do
      member do
        get :remove
      end
    end
    get :assignments, to: 'pages#assignments'
    get :stats , to: 'stats#index'
  end

  get '/account/password' , to: 'users#password_changed'

  get '/:category' , to: 'articles#index' , as: 'category'

end

app/views/shared/_ads.html.erb
<% @u = Update.where(active:true).last %>
<%= link_to (image_tag @u.promo(:medium) , class: "ad"), @u %>

app/views/shared/_alerts.html.erb
<% if flash[:notice] %>
	<script type="text/javascript">
		noty({
			text: "<%= flash[:notice] %>",
			type: 'alert'
		});
	</script>
<% end %>

<% if flash[:alert] %>
	<script type="text/javascript">
		noty({
			text: "<%= flash[:alert] %>",
			type: 'error'
		});
	</script>
<% end %>

<% if flash[:success] %>
	<script type="text/javascript">
		noty({
			text: "<%= flash[:success] %>",
			type: 'success'
		});
	</script>
<% end %>

<% if flash[:error] %>
	<script type="text/javascript">
		noty({
			text: "<%= flash[:error] %>",
			type: 'error'
		});
	</script>
<% end %>

app/views/shared/_latest_articles.html.erb
<div class="widget">
<table class="table table-sidebar">
  <h5>Latest Articles</h5>
  <% Article.first(5).each do |a| %>
    <tr>
      <td><%= link_to a.title , a %></td>
    </tr>
  <% end %>
</table>
</div>

app/views/shared/_latest_stories.html.erb
<div class="widget">
<table class="table table-sidebar">
  <h5>Latest Stories</h5>
  <% Story.where(workflow_state: 'accepted').first(5).each do |s| %>
    <tr>
      <td><%= link_to s.title , s %></td>
    </tr>
  <% end %>
</table>
</div>

app/views/shared/_menu.html.erb
<%#FOR MOBILE %>
<div id="dl-menu" class="dl-menuwrapper visible-xs visible-sm">
	<button class="dl-trigger">Open Menu</button>
	<ul class="dl-menu">

		<% Category.all.order(:weight).each do |c| %>
			<li><%= link_to c.name , category_path(c.slug) %></li>
    <% end %>

		<li>
			<a href="#">More ></a>
			<ul class="dl-submenu">
				<li><%= link_to 'About Us' , page_path('about-us') %></li>
				<li><%= link_to 'Contact Us' , page_path('contact-us') %></li>
			</ul>
		</li>
	</ul>
</div><!-- /dl-menuwrapper -->

<%# FOR EVERYTHING ELSE %>
<div id="navlinks", class="pull-left hidden-xs hidden-sm">
	<%= tabs_tag builder: MenuTabBuilder do |tab| %>
		<% Category.all.order(:weight).each do |c| %>
		  <%= tab.send "#{c.slug}" , c.name , category_path(c.slug) %>
		  <%# tab.opinion 'Social & Morality' , opinions_path %>
		  <%# tab.observation 'Politics' , observations_path %>
		  <%# tab.assignments 'Assignments' , assignments_path %>
  	<% end %>
	<% end %>
</div>

app/views/shared/_meta_tags.html.erb
<title><%= @page_title ? @page_title + ' | Sayaahi.com ' : 'Sayaahi.com' %></title>

<%= analytics_init if Rails.env.production? %>

<% if !@page_description.blank? %>
	<meta name="description" content= "<%= @page_description.tr(?", ?') %>">
	<meta property="og:description" content= "<%= @page_description.tr(?", ?') %>" />
<% end %>

<% @og_image ||= 'sayaahi-og.png' %>
<meta property="og:image" content= "<%= URI.join(root_url, image_path(@og_image)) %>" >
<meta property="fb:app_id" content= "<%= Figaro.env.facebook_application_id %>" />
<meta property="og:title" content= "<%= @page_title %>" />
<meta property="og:type" content= "<%= @og_type || 'article' %>" />
<meta property="og:url" content= "<%= request.original_url %>" />

<%= csrf_meta_tag %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<meta name="theme-color" content="#009b99" />

app/views/shared/_subfooter.html.erb
<% if content_for? :subfooter %> 
  <div id="subfooter_wrapper" class="row">
    <div id="subfooter" style="background-color:<%= @cat.try(:color_light) %>">
      <div class="row"><%= yield :subfooter %></div>
    </div>
  </div>
<% end %>

app/views/shared/_user_links.html.erb
<div id="userlinks" class="center-xs pull-right">
<% if current_user %>
	<div class="badge <%= 'bg-red' if notifications_count > 0 %>">
    <%= link_to notifications_count , notifications_path %>
  </div>
  	Welcome <b><%= current_user.username %></b>
    <span class="dropdown">
      <%= link_to '#' , id: 'dl1' , style:"color:#fff", 'data-toggle'=>'dropdown' do %>
      <span class="glyphicon glyphicon-chevron-down"></span><% end %>
      <ul class="dropdown-menu dropdown-menu-right text-right" role="menu" aria-labelledby="dl1">
        <li role="presentation"><%= link_to 'My Profile' , user_path(current_user) %></li>
        <li role="presentation"><%= link_to 'Settings' , edit_user_registration_path %></li>
				<li role="separator" class="divider"></li>
        <li role="presentation"><%= link_to 'Logout' , destroy_user_session_path , method: :delete %></li>
      </ul>
    </span>

		<% if can? :access , :team_menu %>
			<span class="dropdown">
				<%= link_to '#' , id: 'dl1' , 'data-toggle'=>'dropdown' do %>
				<div class="btn btn-xs btn-primary" id="team_btn">Team</div><% end%>
				<ul class="dropdown-menu dropdown-menu-right text-right" id="team_menu" role="menu" aria-labelledby="dl2">
					<li role="presentation"><%= link_to 'Assignments' , assignments_path %></li>
					<li role="presentation"><%= link_to "New Assign" , new_assignment_path %></li>
				</ul>
			</span>
		<% end %>

		<% if can? :access , :admin_pages %>
			<span class="dropdown">
	      <%= link_to '#' , id: 'dl1' , 'data-toggle'=>'dropdown' do %>
	      <div class="btn btn-xs btn-danger" id="admin_btn">Admin</div><% end%>
	      <ul class="dropdown-menu dropdown-menu-right text-right" id="admin_menu" role="menu" aria-labelledby="dl2">
						<li role="presentation"><%= link_to 'Admin Home' , admin_root_path %></li>
						<li role="presentation"><%= link_to "Articles" , admin_articles_path %></li>
						<li role="presentation"><%= link_to "Comments" , admin_comments_path %></li>
						<li role="presentation"><%= link_to "Pages" , pages_path %></li>
						<li role="presentation"><%= link_to "Categories" , admin_categories_path %></li>
						<li role="presentation"><%= link_to "Updates" , updates_path %></li>
						<li role="presentation"><%= link_to "Errors" , admin_errors_path %></li>
						<li role="presentation"><%= link_to "Stats/Analytics" , admin_stats_path %></li>
						<li role="presentation"><%= link_to "Task types" , admin_task_types_path %></li>
						<li role="presentation"><%= link_to "Mailer" , newsletters_path %></li>
					<li role="presentation"><%= link_to 'Assignments Admin' , admin_assignments_path %></li>
	      </ul>
	    </span>
		<% end %>

<% else %>
  Welcome <b>guest</b> <%= link_to "Login" , new_user_session_path %>
<% end %>
</div>

app/views/shared/_workroom_sidebar.html.erb
<% content_for :subindex_right do %>

<%# STATE %>
  <b>State:</b> <span class="badge"><%= @article.workflow_state %></span></br>

<%# EDITING ASSIGNMENT %>
  <% if @article.editing_assignment %>
  <h5>
    Editor:
    <%= link_to_user @article.editing_assignment.to_id %>
    <span class="badge badge-sm"><%= @article.editing_assignment.status %></span></br>
  </h5>
  <% end %>

<%# SUBEDITING ASSIGNMENT %>
  <% if @article.subediting_assignment %>
  <h5>
    Subeditor:
    <%= link_to_user @article.subediting_assignment.to_id %>
    <span class="badge badge-sm"><%= @article.subediting_assignment.status %></span></br>
  </h5>
  <% end %>

<%# TASKS %>
  <% if @article.custom_assignments.any? %>
    <div id="index_right" class="col-xs-12" style="background-color: <%= @cat.color_light || "#ccc" %>" >
      <h5>Tasks</h5>
      <% @article.custom_assignments.each do |assignment| %>
          <%= link_to assignment.title , assignment %>
          <p class="small">
            Assigned to: <%= link_to assignment.assignee.username , assignment.assignee %> -
            <span class="badge-sm"><%= assignment.status %></span>
          </p>
      <% end %>
    </div>
  <% end %>

<%# javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= javascript_include_tag "http://code.highcharts.com/highcharts.js", "chartkick" %>
  <h3>Visits</h3>
  <%= line_chart @article.events.group_by_day(:time).count %>
<% end %>