config/routes.rb
Rails.application.routes.draw do

  get 'users/autocomplete' , to: 'users#autocomplete'
  get 'articles/:id/edit/crop', to: 'articles#crop' , as: "crop_featured_image"
  get 'updates/:id/edit/crop', to: 'updates#crop' , as: "crop_promo"
  get 'users/:id/edit/crop', to: 'users#crop' , as: "crop_avatar"

  resources :updates
  resources :pages
  resources :users, constraints: {id: /[0-9A-Za-z\-\.]+/ }
  resources :notifications

  resources :assignments do
    member do
      get 'workflow'
    end
  end

  mount Ckeditor::Engine => '/editor'
  resources :newsletters do
    member do
      get :mail
      get :preview
    end
  end

  resources :comments do
    member do
      get :accept
      get :reject
      get :reply
      post :reply
    end
  end

  devise_for :user, :path => 'account', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  root 'pages#home'

  resources :articles , path: 'node' , except: :index do
    member do
      get :workroom
      post :workroom , action: 'workroom_save'
      get 'version/:version', action: 'version' , as: "version"
      delete 'version/:version', action: 'destroy_version' , as: "destroy_version"
      get :assign
      post :assign , action: 'assign_save' , as: 'assign_save'
      patch :assign , action: 'assign_save'
    end
  end

  namespace :admin do
    root to: 'pages#index'
    resources :articles
    resources :comments
    resources :task_types
    resources :errors , except: [:new,:create,:update,:edit]
    resources :categories do
      member do
        get :remove
      end
    end
    get :assignments, to: 'pages#assignments'
    get :stats , to: 'stats#index'
  end

  get '/account/password' , to: 'users#password_changed'

  get '/:category' , to: 'articles#index' , as: 'category'

end

app/models/update.rb
class Update < ActiveRecord::Base

belongs_to :user

before_save :inactivate_others

# PAPERTRAIL
has_paper_trail only: [:title, :body, :intro] , on: [:update]

# PAPERCLIP
has_attached_file :promo,
                  styles: { :large => "800x400>", :medium => "400x200>" }

# VALIDATIONS
validates_presence_of :title , :body
validates_length_of :body , in: 240..25000
validates :promo, :dimensions => { :width => 800, :height => 400 }
validates_attachment  :promo,
                      content_type: { content_type: /\Aimage\/.*\Z/ },
                      size: {in: 0..2500.kilobytes}

# PAPERCROP (ezuhaib/papercrop)
crop_attached_file :promo , min_size:'800x400' , aspect:'2:1'

private

def inactivate_others
	if self.active?
		@active_updates = Update.where(active: true).all
		@active_updates.each do |u|
			u.update_attribute(:active,false)
		end
	end
end

end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  before_action :set_update, only: [:show, :edit, :update, :destroy, :crop]

  respond_to :html

  def index
    authorize! :read , Update
    @page_title  = "News & Updates"
    @page_description = "Updates related to Sayaahi.com itself."
    @updates = Update.order('created_at DESC').page(params[:page]).per(10)
  end

  def show
    @page_title  = @update.title
    @page_description  = teaser(@update.body)
    ahoy.track "readable_content" , {} , trackable: @update unless @update.user == current_user
    respond_with(@update)
  end

  def new
    authorize! :create , Update
    @page_title  = "Creating update"
    @update = Update.new
  end

  def edit
  end

  def create
    authorize! :create , Update
    @update = Update.new(update_params)
    @update.user_id = current_user.id
    if params[:update][:promo] and @update.save
      redirect_to crop_promo_path(@update)
    elsif @update.save
      redirect_to @update
    else
      render :new
    end
  end

  def update
    authorize! :update , Update
    @update.assign_attributes(update_params)
    if params[:update][:promo] and @update.save
      redirect_to crop_promo_path(@update)
    elsif @update.save
      redirect_to @update
    else
      render :update
    end
  end

  def crop
    authorize! :update , @update
    @page_title  = "Article image cropping"
  end

  def destroy
    authorize :destroy , @update
    @update.destroy
    respond_with(@update)
  end

  private
    def set_update
      @update = Update.find(params[:id])
    end

    def update_params
      params.require(:update).permit(:title, :body, :user_id, :active, :promo, cropping_params(:promo))
    end
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/updates/_form.html.erb
<%= bootstrap_form_for @update do |f| %>
    <%= f.text_field :title %>
    <%= f.cktext_area :body %></br>
    <%= f.file_field :promo , help: "Min 800x400px. Max 2.5MB." %>
    <%= f.check_box :active %>
    <%= f.submit :Submit , class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/updates/crop.html.erb
<div class="alert alert-info">
Ideally the image must be made of resolution 800x400 by hand. If it isn't then crop it here.</div>

<%= form_for @update do |f| %>
  <div class="center">
  	<%= f.cropbox :promo , width: 800 %></div></br>
  	<div class='well col-xs-12'>
  		<%= f.crop_preview :promo , width: 350 %>
  			<b>Save if you're satisfied</b></br></br>
  			<%= f.submit 'Save' , class:"btn btn-success btn-lg" %>
  	</div>
<% end %>

app/views/updates/edit.html.erb
<h1>Editing update</h1>

<%= render 'form' %>

app/views/updates/index.html.erb
<h2>News and Updates
<%= link_to 'New Update', new_update_path , class: "btn btn-default" if can? :create , Update %>
</h2>

<table class="table table-striped">
  <tbody>
    <% @updates.each do |update| %>
      <tr>
        <td><%= link_to update.title , update %></td>
        <td><%= pretty_created_at(update) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @updates %>

<% content_for :sidebar do %>
  <div class="alert alert-warning">
    Keep visiting this page to stay in touch with latest News and updates relating to sayaahi.
  </div>
<% end %>

app/views/updates/new.html.erb
<h1>New update</h1>

<%= render 'form' %>

app/views/updates/show.html.erb
<div class="col-xs-12">
  <h1 class="center-xs">
      <%= @update.title %>&nbsp
      <%= link_to 'Edit', edit_update_path(@update) , class: "btn btn-default" if can? :update , @update %>
  </h1>

  <p>
    <%= @update.body.html_safe %>
  </p>
</div>